/*
 * This file is generated by jOOQ.
 */
package fr.flalal.clicker.storage;


import fr.flalal.clicker.storage.tables.Book;


/**
 * Convenience access to all tables in clicker.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>clicker.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
