/*
 * This file is generated by jOOQ.
 */
package fr.flalal.clicker.storage;


import fr.flalal.clicker.storage.tables.Player;


/**
 * Convenience access to all tables in clicker.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>clicker.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;
}
