/*
 * This file is generated by jOOQ.
 */
package fr.flalal.clicker.storage;


import fr.flalal.clicker.storage.tables.Game;
import fr.flalal.clicker.storage.tables.GameGenerator;
import fr.flalal.clicker.storage.tables.Generator;
import fr.flalal.clicker.storage.tables.Player;


/**
 * Convenience access to all tables in clicker.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>clicker.game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>clicker.game_generator</code>.
     */
    public static final GameGenerator GAME_GENERATOR = GameGenerator.GAME_GENERATOR;

    /**
     * The table <code>clicker.generator</code>.
     */
    public static final Generator GENERATOR = Generator.GENERATOR;

    /**
     * The table <code>clicker.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;
}
