/*
 * This file is generated by jOOQ.
 */
package fr.flalal.clicker.storage.tables.records;


import fr.flalal.clicker.storage.tables.Game;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record6<UUID, UUID, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>clicker.game.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>clicker.game.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>clicker.game.player_id</code>.
     */
    public void setPlayerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>clicker.game.player_id</code>.
     */
    public UUID getPlayerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>clicker.game.money</code>.
     */
    public void setMoney(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>clicker.game.money</code>.
     */
    public BigDecimal getMoney() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>clicker.game.manual_click</code>.
     */
    public void setManualClick(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>clicker.game.manual_click</code>.
     */
    public BigDecimal getManualClick() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>clicker.game.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>clicker.game.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>clicker.game.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>clicker.game.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Game.GAME.PLAYER_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Game.GAME.MONEY;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Game.GAME.MANUAL_CLICK;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Game.GAME.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Game.GAME.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getPlayerId();
    }

    @Override
    public BigDecimal component3() {
        return getMoney();
    }

    @Override
    public BigDecimal component4() {
        return getManualClick();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getPlayerId();
    }

    @Override
    public BigDecimal value3() {
        return getMoney();
    }

    @Override
    public BigDecimal value4() {
        return getManualClick();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public GameRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(UUID value) {
        setPlayerId(value);
        return this;
    }

    @Override
    public GameRecord value3(BigDecimal value) {
        setMoney(value);
        return this;
    }

    @Override
    public GameRecord value4(BigDecimal value) {
        setManualClick(value);
        return this;
    }

    @Override
    public GameRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GameRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public GameRecord values(UUID value1, UUID value2, BigDecimal value3, BigDecimal value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(UUID id, UUID playerId, BigDecimal money, BigDecimal manualClick, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Game.GAME);

        setId(id);
        setPlayerId(playerId);
        setMoney(money);
        setManualClick(manualClick);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
