/*
 * This file is generated by jOOQ.
 */
package fr.flalal.clicker.storage.tables.records;


import fr.flalal.clicker.storage.tables.GameGenerator;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameGeneratorRecord extends UpdatableRecordImpl<GameGeneratorRecord> implements Record5<UUID, UUID, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>clicker.game_generator.id_game</code>.
     */
    public void setIdGame(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>clicker.game_generator.id_game</code>.
     */
    public UUID getIdGame() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>clicker.game_generator.id_generator</code>.
     */
    public void setIdGenerator(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>clicker.game_generator.id_generator</code>.
     */
    public UUID getIdGenerator() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>clicker.game_generator.level</code>.
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>clicker.game_generator.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>clicker.game_generator.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>clicker.game_generator.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>clicker.game_generator.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>clicker.game_generator.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return GameGenerator.GAME_GENERATOR.ID_GAME;
    }

    @Override
    public Field<UUID> field2() {
        return GameGenerator.GAME_GENERATOR.ID_GENERATOR;
    }

    @Override
    public Field<Integer> field3() {
        return GameGenerator.GAME_GENERATOR.LEVEL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return GameGenerator.GAME_GENERATOR.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return GameGenerator.GAME_GENERATOR.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getIdGame();
    }

    @Override
    public UUID component2() {
        return getIdGenerator();
    }

    @Override
    public Integer component3() {
        return getLevel();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getIdGame();
    }

    @Override
    public UUID value2() {
        return getIdGenerator();
    }

    @Override
    public Integer value3() {
        return getLevel();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public GameGeneratorRecord value1(UUID value) {
        setIdGame(value);
        return this;
    }

    @Override
    public GameGeneratorRecord value2(UUID value) {
        setIdGenerator(value);
        return this;
    }

    @Override
    public GameGeneratorRecord value3(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public GameGeneratorRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GameGeneratorRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public GameGeneratorRecord values(UUID value1, UUID value2, Integer value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameGeneratorRecord
     */
    public GameGeneratorRecord() {
        super(GameGenerator.GAME_GENERATOR);
    }

    /**
     * Create a detached, initialised GameGeneratorRecord
     */
    public GameGeneratorRecord(UUID idGame, UUID idGenerator, Integer level, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(GameGenerator.GAME_GENERATOR);

        setIdGame(idGame);
        setIdGenerator(idGenerator);
        setLevel(level);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
