/*
 * This file is generated by jOOQ.
 */
package fr.flalal.clicker.storage.tables.records;


import fr.flalal.clicker.storage.tables.Generator;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeneratorRecord extends UpdatableRecordImpl<GeneratorRecord> implements Record4<UUID, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>clicker.generator.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>clicker.generator.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>clicker.generator.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>clicker.generator.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>clicker.generator.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>clicker.generator.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>clicker.generator.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>clicker.generator.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Generator.GENERATOR.ID;
    }

    @Override
    public Field<String> field2() {
        return Generator.GENERATOR.NAME;
    }

    @Override
    public Field<String> field3() {
        return Generator.GENERATOR.DESCRIPTION;
    }

    @Override
    public Field<Boolean> field4() {
        return Generator.GENERATOR.ENABLED;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Boolean component4() {
        return getEnabled();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Boolean value4() {
        return getEnabled();
    }

    @Override
    public GeneratorRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public GeneratorRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GeneratorRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GeneratorRecord value4(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public GeneratorRecord values(UUID value1, String value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GeneratorRecord
     */
    public GeneratorRecord() {
        super(Generator.GENERATOR);
    }

    /**
     * Create a detached, initialised GeneratorRecord
     */
    public GeneratorRecord(UUID id, String name, String description, Boolean enabled) {
        super(Generator.GENERATOR);

        setId(id);
        setName(name);
        setDescription(description);
        setEnabled(enabled);
    }
}
