/*
 * This file is generated by jOOQ.
 */
package fr.flalal.clicker.storage.tables.records;


import fr.flalal.clicker.storage.enums.UserRoleType;
import fr.flalal.clicker.storage.tables.Player;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> implements Record6<UUID, String, String, String, String, UserRoleType> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>clicker.player.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>clicker.player.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>clicker.player.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>clicker.player.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>clicker.player.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>clicker.player.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>clicker.player.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>clicker.player.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>clicker.player.pseudonym</code>.
     */
    public void setPseudonym(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>clicker.player.pseudonym</code>.
     */
    public String getPseudonym() {
        return (String) get(4);
    }

    /**
     * Setter for <code>clicker.player.role</code>.
     */
    public void setRole(UserRoleType value) {
        set(5, value);
    }

    /**
     * Getter for <code>clicker.player.role</code>.
     */
    public UserRoleType getRole() {
        return (UserRoleType) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, String, String, UserRoleType> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, String, String, UserRoleType> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Player.PLAYER.ID;
    }

    @Override
    public Field<String> field2() {
        return Player.PLAYER.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Player.PLAYER.LAST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Player.PLAYER.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Player.PLAYER.PSEUDONYM;
    }

    @Override
    public Field<UserRoleType> field6() {
        return Player.PLAYER.ROLE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getPseudonym();
    }

    @Override
    public UserRoleType component6() {
        return getRole();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getPseudonym();
    }

    @Override
    public UserRoleType value6() {
        return getRole();
    }

    @Override
    public PlayerRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public PlayerRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public PlayerRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public PlayerRecord value5(String value) {
        setPseudonym(value);
        return this;
    }

    @Override
    public PlayerRecord value6(UserRoleType value) {
        setRole(value);
        return this;
    }

    @Override
    public PlayerRecord values(UUID value1, String value2, String value3, String value4, String value5, UserRoleType value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(UUID id, String firstName, String lastName, String email, String pseudonym, UserRoleType role) {
        super(Player.PLAYER);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setPseudonym(pseudonym);
        setRole(role);
    }
}
