server:
  port: 8080

spring:
  flyway:
    schemas:
      - clicker
  application:
    name: clicker-api
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://192.168.1.26:5432/clicker_db
    username: clicker_api
    password: password

clicker-api:
  average-human-click-per-second: 10