server:
  port: 8080

spring:
  flyway:
    schemas:
      - clicker
  application:
    name: clicker-api
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/clicker_db
    username: clicker_api
    password: password